[package]
name = "todo-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.20"
gloo-net = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["HtmlInputElement"] }
